services:
  - type: web
    name: realtimeohgiri-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://realtimeohgiri.netlify.app
      - key: ALLOWED_ORIGINS
        value: "https://realtimeohgiri.netlify.app,http://localhost:3000"
    healthCheckPath: /health
    autoDeploy: true 